# Generated by Django 2.2.12 on 2022-11-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='Jenis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Jenis'),
        ),
    ]
