# Generated by Django 2.2.12 on 2022-11-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_barang_jenis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='perpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodebuku', models.CharField(max_length=8)),
                ('namabuku', models.CharField(max_length=50)),
                ('stokbuku', models.IntegerField()),
                ('hargabuku', models.BigIntegerField()),
                ('penerbit', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
