# Generated by Django 2.2.12 on 2022-11-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_perpus'),
    ]

    operations = [
        migrations.CreateModel(
            name='makanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Jenis')),
            ],
        ),
        migrations.DeleteModel(
            name='Detailtrans',
        ),
        migrations.DeleteModel(
            name='perpus',
        ),
    ]
